### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Zenas22** [Zenas22/athena#2]

**Comment by mzambia70** [comment]
cheki bro fon imezima ukiai kitu yoyote weh nitumiye kwa text

**Comment by Zenas22** [comment]
Moha ebu tuma icon kwa Miano

**Comment by Zenas22** [comment]
Alafu hizi mapage za wasee haziko indented fiti sijui sasa wanadai aje

**Comment by Zenas22** [comment]
Ngori man
