### ISSUE TITLE
Criteria pages - HTML

### ISSUE THREAD

**Issue by Zenas22** [Zenas22/athena#4]

**Comment by Zenas22** [comment]
The pages lack the icon chosen by Moha

**Comment by mi-ano** [comment]
Which icon?

**Comment by Zenas22** [comment]
Icon chosen by Mohamed that we declared in the morning. Also indentation is really giving me a hard time

**Comment by mi-ano** [comment]
Is it okay if I do to tomorrow

**Comment by mzambia70** [comment]
[image: athena.gif]

**Comment by mzambia70** [comment]
that is the logo

**Comment by Zenas22** [comment]
Iko sawa
